.TH SYSTEM-CONFIG-DATE 8 "Wed 13 June 2001" "Linux" "Date/Time Properties"
.UC 4
.SH 名前
system-config-date \- システムの日付と時刻を調整するグラフィカルなインターフェース
.SH 書式
\fBsystem-config-date\fR 
.SH 説明
\fBsystem-config-date\fR はユーザがシステムの日付と時刻を設定できるツールを提供します。
それ以外にもユーザはシステムのタイムゾーンを設定したり、NTPタイムサーバを使って
システムの時刻を同期させるNTPデーモンを設定できます。

.SH オプション
なし
.SH ファイル
\fI/usr/bin/system-config-date\fP
.br
\fI/usr/share/system-config-date/*\fP
.br
.SH 例
プログラムを実行するには:
.LP
system-config-date
.LP
と入力します。

.SH バグレポート
バグは<http://bugzilla.redhat.com>に報告してください。

.SH 著者
.nf
Brent Fox <bfox@redhat.com>
Tammy Fox <tfox@redhat.com>
Michael Fulbright <msf@redhat.com>
.fi
