.\" .UC 4
.TH "SYSTEM-CONFIG-DATE" "8" "Wed 13 June 2001" "Linux" "Date/Time Properties"
.SH "NAME"
system-config-date \- Interface graphique pour changer la date et l'heure du systeme
.SH "SYNOPSIS"
\fBsystem-config-date\fR 
.SH "DESCRIPTION"
\fBsystem-config-date\fR offre une interface graphique qui permet aux utilisateurs
de changer la date et l'heure du system. Il permet aussi a l'utilisateur
de configurer la zone horaire du systeme ainsi que d'installer le service
NTP afin qu'il synchronise l'heure du system avec un serveur NTP.

.SH "OPTIONS "
None
.SH "FICHIERS"
\fI/usr/bin/system-config-date\fP
.br 
\fI/usr/share/system-config-date/*\fP
.br 

.SH "EXEMPLES"
Pour lancer le programme, taper :
.LP 
system-config-date
.LP 

.SH "BUGS"
Reporter les bugs a <http://bugzilla.redhat.com>.

.SH "AUTEURS"
.nf 
Brent Fox <bfox@redhat.com>
Tammy Fox <tfox@redhat.com>
Michael Fulbright <msf@redhat.com>
.fi 






