.TH DATECONFIG 8 "Wed 13 June 2001" "Linux" "Date/Time Properties"
.UC 4
.SH NAME
system-config-date \- graphical interface for changing system date and time
.SH SYNOPSIS
\fBsystem-config-date\fR 
.SH DESCRIPTION
\fBsystem-config-date\fR provides a graphical interface that allows the user 
to change the system date and time. It also allows the user to configure 
the system time zone and to setup the NTP daemon to synchronize the time 
of the system with a NTP time server.

.SH OPTIONS 
None
.SH FILES
\fI/usr/bin/system-config-date\fP
.br
\fI/usr/share/system-config-date/*\fP
.br
.SH EXAMPLES
To run the program type:
.LP
system-config-date
.LP

.SH "REPORTING BUGS"
Report bugs to <http://bugzilla.redhat.com>.

.SH AUTHORS
.nf
Brent Fox <bfox@redhat.com>
Tammy Fox <tfox@redhat.com>
Michael Fulbright <msf@redhat.com>
.fi






